version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: my_sql
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password 
      MYSQL_DATABASE: cmc
      MYSQL_USER: peter
      MYSQL_PASSWORD: 123456
volumes:
  mysql_data:
  # Using created volume
    external: true
