version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: my_sql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 123456A
      MYSQL_DATABASE: cmc
      MYSQL_USER: peter
      MYSQL_PASSWORD: 123456A
networks:
  default:
    name: my_sql
